site_name: WasmDNN
nav:
  - 'Home': 'index.md'
  - 'Architecture': 'architecture.md'
  - 'Features': 'features.md'
theme:
  name: 'material'
  palette:
    primary: 'light green'
    accent: 'light green'
